//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace UndertaleModTool.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UndertaleModTool.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Back に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Data に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Data {
            get {
                return ResourceManager.GetString("Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Audio groups に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Data_AudioGroups {
            get {
                return ResourceManager.GetString("Data_AudioGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Backgrounds &amp;amp; Tile sets に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Data_BGAndTileSets {
            get {
                return ResourceManager.GetString("Data_BGAndTileSets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Code に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Data_Code {
            get {
                return ResourceManager.GetString("Data_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Code locals (unused?) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Data_CodeLocals {
            get {
                return ResourceManager.GetString("Data_CodeLocals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Embedded audio に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Data_EmbeddedAudio {
            get {
                return ResourceManager.GetString("Data_EmbeddedAudio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Embedded images に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Data_EmbeddedImages {
            get {
                return ResourceManager.GetString("Data_EmbeddedImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Embedded textures に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Data_EmbeddedTextures {
            get {
                return ResourceManager.GetString("Data_EmbeddedTextures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Extensions に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Data_Extensions {
            get {
                return ResourceManager.GetString("Data_Extensions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Fonts に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Data_Fonts {
            get {
                return ResourceManager.GetString("Data_Fonts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Functions に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Data_Functions {
            get {
                return ResourceManager.GetString("Data_Functions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Game objects に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Data_GameObjects {
            get {
                return ResourceManager.GetString("Data_GameObjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   General Info に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Data_GeneralInfo {
            get {
                return ResourceManager.GetString("Data_GeneralInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Gloval init に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Data_GlobalInit {
            get {
                return ResourceManager.GetString("Data_GlobalInit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Paths に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Data_Paths {
            get {
                return ResourceManager.GetString("Data_Paths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Rooms に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Data_Rooms {
            get {
                return ResourceManager.GetString("Data_Rooms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Scripts に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Data_Scripts {
            get {
                return ResourceManager.GetString("Data_Scripts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Shaders に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Data_Shaders {
            get {
                return ResourceManager.GetString("Data_Shaders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sounds に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Data_Sounds {
            get {
                return ResourceManager.GetString("Data_Sounds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sprites に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Data_Sprites {
            get {
                return ResourceManager.GetString("Data_Sprites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Strings に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Data_Strings {
            get {
                return ResourceManager.GetString("Data_Strings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Texture group information に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Data_TextureGroupInformation {
            get {
                return ResourceManager.GetString("Data_TextureGroupInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Texture page items に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Data_TexturePageItems {
            get {
                return ResourceManager.GetString("Data_TexturePageItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Timelines に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Data_TimeLines {
            get {
                return ResourceManager.GetString("Data_TimeLines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Variables に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Data_Variables {
            get {
                return ResourceManager.GetString("Data_Variables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Language に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _File に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Menu_File {
            get {
                return ResourceManager.GetString("Menu_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Batch decompile に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Menu_File_BatchDecompile {
            get {
                return ResourceManager.GetString("Menu_File_BatchDecompile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Close に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Menu_File_Close {
            get {
                return ResourceManager.GetString("Menu_File_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Export to GameMaker project に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Menu_File_ExportToGameMakerProject {
            get {
                return ResourceManager.GetString("Menu_File_ExportToGameMakerProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Generate o_ffset map に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Menu_File_GenerateOffsetMap {
            get {
                return ResourceManager.GetString("Menu_File_GenerateOffsetMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _New に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Menu_File_New {
            get {
                return ResourceManager.GetString("Menu_File_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Open に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Menu_File_Open {
            get {
                return ResourceManager.GetString("Menu_File_Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Run game に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Menu_File_RunGame {
            get {
                return ResourceManager.GetString("Menu_File_RunGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Run game under _debugger に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Menu_File_RunGameUnderDebugger {
            get {
                return ResourceManager.GetString("Menu_File_RunGameUnderDebugger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Save に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Menu_File_Save {
            get {
                return ResourceManager.GetString("Menu_File_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   S_ettings に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Menu_File_Settings {
            get {
                return ResourceManager.GetString("Menu_File_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Help に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Menu_Help {
            get {
                return ResourceManager.GetString("Menu_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _About に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Menu_Help_About {
            get {
                return ResourceManager.GetString("Menu_Help_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _GitHub に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Menu_Help_GitHub {
            get {
                return ResourceManager.GetString("Menu_Help_GitHub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Scripts に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Menu_Scripts {
            get {
                return ResourceManager.GetString("Menu_Scripts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Run builtin script に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Menu_Scripts_RunBuiltinScript {
            get {
                return ResourceManager.GetString("Menu_Scripts_RunBuiltinScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   (...loading...) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Menu_Scripts_RunBuiltinScript_Loading {
            get {
                return ResourceManager.GetString("Menu_Scripts_RunBuiltinScript_Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Run _other script... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Menu_Scripts_RunOtherScript {
            get {
                return ResourceManager.GetString("Menu_Scripts_RunOtherScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Search に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Settings に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Game Maker: Studio 1.4 path に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_GMS14Path {
            get {
                return ResourceManager.GetString("Settings_GMS14Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Tested to work with v1.4.1773, which is close to release date of latest Undertale patch. Required only if you want to run the game under debugger. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_GMS14Path_ToolTip {
            get {
                return ResourceManager.GetString("Settings_GMS14Path_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   GraphViz path に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_GraphVizPath {
            get {
                return ResourceManager.GetString("Settings_GraphVizPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Required if you want code decompile graphs に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_GraphVizPath_ToolTip {
            get {
                return ResourceManager.GetString("Settings_GraphVizPath_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Welcome to UndertaleModTool! に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string WelcomeToUndertaleModTool {
            get {
                return ResourceManager.GetString("WelcomeToUndertaleModTool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Open data.win file to get started, then double click on the items on the left to view them に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string WelcomeToUndertaleModTool_Description {
            get {
                return ResourceManager.GetString("WelcomeToUndertaleModTool_Description", resourceCulture);
            }
        }
    }
}
